describe('Opens wikipedia website and search for Estación de Atocha-Cercanías page', () => {
    it('Opens wikipedia website and check the language is Spanish', () => {
        cy.visit('https://www.wikipedia.org/')
        cy.contains('Español')
        cy.get('#js-link-box-es')
        .click()
    })
    it('Searches text "atocha" in Spanish Wikipedia', () => {
        cy.get('#searchInput')
        .type('atocha')
        cy.get('#searchButton')
        .click()
        cy.url()
        .should('include', 'https://es.wikipedia.org/wiki/Atocha')
    })
    it('Selects "Atocha-Cercanías" link', () =>{
        cy.contains('Atocha')
        cy.get('a[title="Estación de Atocha-Cercanías"]')
        .eq(0)
        .should('to.have.attr', 'href', '/wiki/Estaci%C3%B3n_de_Atocha-Cercan%C3%ADas')
        .click({ multiple: true })
    })
    it('Check the image is present on the "Atocha-Cercanias" page', () => {
        cy.get('img[alt="Estación de Atocha (Madrid) 02.jpg"]')
        .should('be.visible')
        cy.screenshot('my-image')
    })
    it('Checks the presence and contain of Situacion ferrovialia list on the page', () => {
        cy.get('#mw-content-text  ul:nth-child(7) > li')
        .should('exist')
        .eq(0)
        .should('to.contain.text', 'punto kilométrico 0,0.')
        cy.get('#mw-content-text  ul:nth-child(7) > li')
        .eq(1)
        .should('to.have.descendants', 'a')
        cy.get('#mw-content-text  ul:nth-child(7) > li')
        .eq(2)
        .should('contain', ', punto kilométrico 7,5.')
        cy.screenshot('my-image1')
    })
})