# This is a basic workflow to help you get started with Actions

name: Cypress Tests

on: [push]
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install
        run: npm install
      - name: Api setup
        run:  npm run api
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
        
  
