# This is a basic workflow to help you get started with Actions

name: Cypress Tests

on: [push]
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: |
            npm run api
            npm run test

      - name: Output test results
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
        
  
