# This is a basic workflow to help you get started with Actions

name: Cypress Tests

on: [push]
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Api setup
        uses: cypress-io/github-action@v4
        with:
          api: npm run api
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
        
  
