# This is a basic workflow to help you get started with Actions

name: Cypress Tests

on: 
  push:
      branches:
      - main
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run test

      - name: Output test results
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: mochawesome-report/mochawesome.html
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
  
