# This is a basic workflow to help you get started with Actions

name: Cypress Tests

on: [push]
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Instal dependencies
        with: npm install
      - name: Run api server
        with: npm run api
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run test
        
  
